### ISSUE TITLE
Hover state not working 

### ISSUE THREAD

**Issue by jesspaget** [jesspaget/jesspaget.ca#18]
@thomasjbradley 

Hey Thomas I know it's a busy time for you so if you can't reply I totally understand! 
I am just having trouble with my hover state for my portfolio divs 
I've tried a few different ways to see if it will work but nothing seems to be happening no matter what I try

Here is my code : 
Thanks! 

<img width="983" alt="screen shot 2015-11-12 at 12 37 20 pm" src="https://cloud.githubusercontent.com/assets/6373211/11125886/5768ebe0-893a-11e5-8a04-c311f83a531a.png">
<img width="247" alt="screen shot 2015-11-12 at 12 37 00 pm" src="https://cloud.githubusercontent.com/assets/6373211/11125887/577b4e98-893a-11e5-90c1-5e04f66d62d2.png">

**Comment by thomasjbradley** [comment]
What are you trying to get it to do?

The code looks okay, but I don't think you'll be able to see anything because the `background-color` will be behind the image itself.

**Comment by jesspaget** [comment]
Thanks for getting back to me, Thomas.

Before I had it doing 
opacity: 50% ;

just to see if it works but I wasn't seeing anything changing. I want it to end up having a low opacity and say the title of the project name when hovering.

**Comment by jesspaget** [comment]
I watched your hover box tutorial on youtube and figured a way that I liked using that method! Thanks, again.

**Comment by thomasjbradley** [comment]
Okay, cool.
